apiVersion: v1
kind: configMap
metadata:
  name: backend
  namespace: expense
data:
  DB_HOST: mysql # mysql service component 
---
kind: Deployment
apiVersion: apps/v1
metadata: 
  name: backend
  namespace: expense
# Deployment lables
  labels: 
    component: backend
    project: expense
    tier: app
  
spec: 
  replicas: 2
  selector:
    matchLables:
      component: backend
      project: expense
      tier: app

# pod definition

  template:
    metadata:
      labels:
        component: backend
        project: expense
        tier: app

    spec: 
      containers:
      - name: backend
        image: vasanth135/backend:v1.0
        envFrom:
        - configMapRef:
            name: backend
      
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense

spec:
  selector: 
    component: backend
    project: expense
    tier: app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

