kind: Deployment
apiVersion: apps/v1
metadata: 
  name: mysql
  namespace: expense
# Deployment lables
  labels: 
    component: mysql
    project: expense
    tier: db
  
spec: 
  replicas: 2
  selector:
    matchLables:
      component: mysql
      project: expense
      tier: db

# pod definition

  template:
    metadata:
      labels:
        component: mysql
        project: expense
        tier: db

    spec: 
      containers:
      - name: mysql
        image: vasanth135/mysql:v1.0
      readinessProbe:
        tcpSocket:
          port: 3306
        intialDelaySeconds: 10
        periodSeconds: 5
      livenessProbe:
        tcpSocket:
          port: 3306
        intialDelaySeconds: 10
        periodSeconds: 5
      
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: expense

spec:
  selector: 
    component: mysql
    project: expense
    tier: db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306

